### ISSUE TITLE
Can't find host

### ISSUE THREAD

**Issue by orcavia** [XITRIX/Moonlight-Switch#155]
So i tired this program [`this program`](https://github.com/DuoStream/Duo)
**Note: The program is not open source I don't recommended anyone use that's program**

It's work by creating new instance in the background
for headless streaming.

The issue is Moonlight switch doesn't find the host instance that i create in the Duo but in other devices (connected in same network) like in Moonlight Android it can easily find the host and work normally.

it's maybe specifically issue but would be helpful if this issue can be addressed.
In my opinion using Duo it's much better than use virtual machine (spesialy GPU matters) because it's work natively on windows.
So i would really appreciate if this issue is possible to fix.
Thanks in advance.

**Comment by XITRIX** [comment]
I tried to install it Duo, but it broke my laptop's brain and it started constantly thinking that it's a tablet (it could be tablet, my laptop is transformer) and made it's accelerometer stop rotating screen, also I was not able to start it and reach the web interface of Sunshine. Not sure what I've made wrong, but I had no enough time to experiment with it more. 
 
As a rough guess, probably it not work because Moonlight-Switch does not support custom ports. I think to make it possible to run several instances of Sunshine, Duo runs them using custom ports, and here Moonlight-Switch fails.

**Comment by orcavia** [comment]
Hi, have your laptop okay?
I really appreciate you trying to address the issue.
I am sorry to hear that your laptop has a problem after installing Duo.

Sorry if i write the issue it's not clear enough,
I mean the issue it's not just in Duo but sometimes in virtual machines as well, when other devices can find the host but on Switch sometimes can't find it at all.
And when input manually it gets an error time out.

and yeah probably this is the port problem.
As for a solution, is it possible to be able to add custom port value?
Or at least the port value can be edited in settings.js

**Comment by XITRIX** [comment]
Yes, my laptop is fine after uninstalling DUO.

I think the only solution is to support custom ports. It has to be implemented anyway, not only for DUO. I'll try to manage it when I'll have enough time for it (I'm not sure that it's a quick thing to implement).

**Comment by XITRIX** [comment]
In case this issue is related to custom port feature, I'll close this one and make a link to already existing one #93

**Comment by tuandinh0801** [comment]
You can set moonlight port on DUO to 47989 and it will works for switch, I'm using fine with my switch
