### ISSUE TITLE
Option to disable and forward home button to host

### ISSUE THREAD

**Issue by gotwig** [XITRIX/Moonlight-Switch#157]
Its annoying to leave the session by accident by pressing the home button.

Is this possible?

**Comment by XITRIX** [comment]
It is possible to disable home button, but impossible to process it as normal button to sent any event by it (I really wanted to use it as Guide button), btw I never clicked home button by accident, I also wonder how are you playing normal Switch games without this "issue" :D

To be honest I'd prefer to not disable it, because in case something will go wrong, you'll stuck in the app and will need to reboot your console

**Comment by XITRIX** [comment]
I was wrong.
Implemented in v1.2.2
