### ISSUE TITLE
[Bug] Cannot Connect Over Internet

### ISSUE THREAD

**Issue by fullKTRL** [XITRIX/Moonlight-Switch#161]
Streaming locally while connected to the same network as my PC works perfectly fine, but when trying to stream over Internet (if my switch is connected to a different network), the status indicates "Unable" with the "Wake Up" option, which doesn't do anything. Works with my other devices that have Moonlight (iPhone and iPad).

**Comment by XITRIX** [comment]
Not sounds related to Moonlight-Switch app tbh, if it works locally, it will works remotely (if everything setted up properly) because from network point of view it does not matter.

How did you add your device to pairing list? Did you entered it's remote IP manually, or just added it by auto search?

**Comment by XITRIX** [comment]
I'll close this issue because it is not related to app itself, if still have issues, feel free to ask, also you can check Discord channel, maybe someone will be able to help
