### ISSUE TITLE
Bad connection on switch

### ISSUE THREAD

**Issue by popi0220** [XITRIX/Moonlight-Switch#205]
Latest version installed on my switch, good wifi and right next to the router, but always having bad connection and lag issues

**Comment by popi0220** [comment]
Not really wanting to oc the CPU, it's just that I've seen multiple tutorials and posts where people just put it under 10 and don't have any problems. Just wondering if any setup would solve the problem or maybe the latest version is causing some problem idk

**Comment by popi0220** [comment]
Do you have any trusti tutorial or anything that may make it work on my v1? I'll try to find a solution today but it felt impossible to fix yesterday. Thanks for the tips :)

**Comment by XITRIX** [comment]
it's VERY easy to OC Switch, you can use [Sys-Clk](https://github.com/retronx-team/sys-clk), it has nice Tesla overlay where you can change any OC settings.
Actually they are all safe, it's barely impossible to kill switch using it, because it does not push Switch to it's limits even close. For Moonlight you will need to OC CPU only, it's the only bottleneck there, and you don't need to OC it to maximum values, just a little bit to allow decoded frame pass throw CPU without delays

**Comment by popi0220** [comment]
Just OC my switch and even with the max CPU value I keep getting the bad connection, dont know any recomended settings for a v1 and I haven't seen anyone with the same problem. I will try again later

**Comment by XITRIX** [comment]
Sounds weird ... btw, it should work fine with 720p 10Mbps without any OC, if it cannot, definitely something else is the reason

**Comment by popi0220** [comment]
I'll keep checking, but for now it doesn't seem to work smooth, will try with an ethernet cable this weekend and come back to say if it works hopefully

**Comment by popi0220** [comment]
Update, turns out i just needed an ethernet cable, running pretty smooth. Thanks for all the help!!!
