### ISSUE TITLE
Controller doesn't work as gamepad: Button Press Blocked

### ISSUE THREAD

**Issue by Shekan** [XITRIX/Moonlight-Switch#29]
### Configuration:
I'm on Atmosphere 1.1.1 HOS 13.0, using latest version of Moonlight-Switch (v0.10) with switch docked.

### Problem
I can successfully connect to host machine, but no input is registered unless I switch to mouse mode. I turned on the Debug view and it gives me the following logs when I press buttons on the controller (and not in mouse mode):
```
0 button press blocked (tokens=1)
1 button press blocked (tokens=1)
19 button press blocked (tokens=1)
```
The number at the beginning of each line changes depending on the button/input.

**Comment by XITRIX** [comment]
It's not correct, this messages in debug window means, that buttons blocked to the UI and only uses for streaming, so you will not close streaming window by pressing 'B'.
Try to use any other moonlight client to check, if it's only Moonlight-Switch problem, or it's your Host machine's one.
Mouse mode works, so that means streaming works properly, try to check your Host machine, is there a virtual gamepad created, if not... try to reboot your PC, or reinstall Nvidia Experience.

**Comment by Shekan** [comment]
I tried another moonlight client and it worked as expected. I checked the logs on my host machine to see if it was receiving any input at all while using moonlight-switch, and it **only** registered any input while in mouse mode. Other than that, there were no indications that it had received any input from the client whatsoever. I did not see any virtual gamepad created after connecting from my switch. 

I'll try rebooting and re-installing and let you know if there are any changes, but thus far it appears to be a client-side problem.

**Comment by ncesar** [comment]
Hi. This is also happening with me, which client fixed your issue?
I don't know if this is related but since my GPU is AMD, I have to use https://github.com/loki-47-6F-64/sunshine

**Comment by ncesar** [comment]
Hey guys, just figured out.
All you have to do is install https://github.com/ViGEm/ViGEmBus/releases

and it works with moonlight or sunshine 👯‍♀️

**Comment by Vaddum** [comment]
Lot of people are actually having issues about gamepad disconnecting on OFW 13.0 with last AMS releases. Otherwise I do not know if it is linked.
