### ISSUE TITLE
Wake On LAN not working

### ISSUE THREAD

**Issue by calvinbui** [XITRIX/Moonlight-Switch#71]
Hi, the Wake On LAN feature in this application does not work for me. I've enabled debug logging, but there aren't any meaningful messages there.

This feature works on both Moonlight on Android and Moonlight on macOS.

I've set up a proxy and do not see any Wake On LAN traffic coming through either. Traffic from the Android and macOS versions are logged and are visible.

**Comment by icefox1983** [comment]
Moonlight-Switch does not have Wake on LAN right? Moonlight-NX does, but it doesn't work. Maybe you wanted to comment on that one.

XITRIX, if possible, please implement Wake on Lan and your app would be nearly perfect!

**Comment by XITRIX** [comment]
I'm not sure why it could not work, cause it was just copypasted from Moonlight-NX...
Also I have no devise to test it, my laptop have broken sleep mode, so I don't know how to check if it works or not

**Comment by icefox1983** [comment]
> 

Sorry but you mean moonlight-switch has wake on lan functionality? Where exactly, I didn’t find it

**Comment by icefox1983** [comment]
oh I found it. Indeed it doesn't work. and masagrator noted on my commend under moonlight-nx that HOS doesn't supported. I don't understand how, but I guess that's it. I've installed an iPhone app to wake up the PC. Just one extra step, not too bad.

**Comment by gaaat98** [comment]
@XITRIX Hi! The problem with WOL lies in the fact that the magic packet is being sent to the server address instead of a broadcast address (such as 255.255.255.255), many routers drop the packet if the destination host is not available. In fact when pressing "Wake Up" with the server online, the packet arrives to the destination (confirmed by tcpdump).

Fixing it is a matter of setting the destination address to 255.255.255.255 in these two lines
https://github.com/XITRIX/Moonlight-Switch/blob/6d6338e1d6b501f0f7b66abb7a43c568d36891a3/app/src/streaming/WakeOnLanManager.cpp#LL100C1-L100C65

https://github.com/XITRIX/Moonlight-Switch/blob/6d6338e1d6b501f0f7b66abb7a43c568d36891a3/app/src/streaming/WakeOnLanManager.cpp#LL143C1-L143C65

I tried to implement it myself but I wasn't able to build successfully (linking always fails in some way), if you end up fixing it, could you please also add a release? Thanks for your work!

**Comment by XITRIX** [comment]
@gaaat98, yes, broadcast is not working on Switch for unknown reason, that's why searching for a host was made via pinging all possible IP in the current subnetwork, while on PC the same code was able to find all hosts with no problem...

Btw, I'm not sure if I'll find some time to fix this in near future, if you'll be able to fix it, hope you'll create a nice PR, I'll be really grateful for that

**Comment by XITRIX** [comment]
Fixed in #98, thanks to @gaaat98
